import { defineConfig } from 'vite-plus'

const ignorePatterns = [
  'node_modules',
  'dist',
  'report',
  'coverage',
  '**/*.d.ts',
  '.github',
  'README.md',
  'articles',
]

export default defineConfig({
  staged: { '*': 'vp check --fix' },
  pack: {
    clean: true,
    dts: true,
    entry: ['src/index.ts'],
    format: ['esm'],
    outExtensions: () => ({ dts: '.d.ts', js: '.js' }),
    sourcemap: true,
  },
  fmt: { ignorePatterns, objectWrap: 'collapse', semi: false, singleQuote: true },
  lint: {
    categories: {
      correctness: 'error',
      suspicious: 'error',
      perf: 'error',
      restriction: 'error',
      style: 'error',
      pedantic: 'error',
      nursery: 'off',
    },
    ignorePatterns,
    options: { typeAware: true, typeCheck: true },
    rules: {
      'consistent-type-definitions': 'allow',
      'capitalized-comments': 'allow',
      'eslint/max-classes-per-file': ['error', { max: 10 }],
      'eslint/max-lines-per-function': [
        'error',
        { max: 220, skipBlankLines: false, skipComments: false, IIFEs: false },
      ],
      'eslint/max-statements': ['error', { max: 35 }],
      'max-lines': 'allow',
      'explicit-function-return-type': 'allow',
      'func-names': 'allow',
      'func-style': 'allow',
      curly: 'allow',
      'id-length': 'allow',
      'new-cap': 'allow',
      'no-async-await': 'allow',
      'no-duplicate-imports': 'allow',
      'no-inline-comments': 'allow',
      'no-magic-numbers': 'allow',
      'no-optional-chaining': 'allow',
      'no-ternary': 'allow',
      'no-undefined': 'allow',
      'no-use-before-define': 'allow',
      'prefer-destructuring': 'allow',
      'prefer-readonly-parameter-types': 'allow',
      'require-await': 'allow',
      'sort-imports': 'allow',
      'sort-keys': 'allow',
      'strict-void-return': 'allow',
      '@typescript-eslint/ban-types': 'allow',
      '@typescript-eslint/no-base-to-string': 'allow',
      '@typescript-eslint/no-deprecated': 'allow',
      '@typescript-eslint/no-explicit-any': 'allow',
      '@typescript-eslint/no-misused-promises': 'allow',
      '@typescript-eslint/no-invalid-void-type': 'allow',
      '@typescript-eslint/no-unnecessary-type-arguments': 'allow',
      '@typescript-eslint/no-unnecessary-type-parameters': 'allow',
      '@typescript-eslint/no-unsafe-type-assertion': 'allow',
      '@typescript-eslint/parameter-properties': 'allow',
      '@typescript-eslint/promise-function-async': 'allow',
      'unicorn/filename-case': ['error', { case: 'kebabCase' }],
      'unicorn/no-array-callback-reference': 'allow',
      'unicorn/no-null': 'allow',
      'unicorn/no-thenable': 'allow',
      'unicorn/no-useless-undefined': 'allow',
      yoda: 'allow',
    },
    overrides: [
      {
        files: ['**/tests/**', '**/test/**'],
        rules: {
          'prefer-readonly-parameter-types': 'allow',
          'prefer-template': 'allow',
          'no-shadow': 'allow',
          '@typescript-eslint/strict-boolean-expressions': 'allow',
          '@typescript-eslint/return-await': 'allow',
          '@typescript-eslint/await-thenable': 'allow',
          '@typescript-eslint/no-explicit-any': 'allow',
          '@typescript-eslint/no-confusing-void-expression': 'allow',
          '@typescript-eslint/no-unsafe-type-assertion': 'allow',
          '@typescript-eslint/require-await': 'allow',
          'eslint/max-depth': 'allow',
          'eslint/no-await-in-loop': 'allow',
          'max-depth': 'allow',
          'max-lines': ['error', { max: 2000, skipBlankLines: true, skipComments: true }],
          'max-lines-per-function': 'allow',
          'no-async-await': 'allow',
          'no-constant-condition': 'allow',
          'no-console': 'allow',
          'no-lonely-if': 'allow',
          'no-magic-numbers': 'allow',
          'no-new': 'allow',
          'no-undefined': 'allow',
          'unicorn/consistent-function-scoping': 'allow',
          'unicorn/custom-error-definition': 'allow',
          'unicorn/no-await-expression-member': 'allow',
          'unicorn/prefer-event-target': 'allow',
        },
      },
    ],
  },
  test: {
    coverage: {
      exclude: ['node_modules/', 'dist/', 'tests/'],
      reporter: ['text', 'json', 'html', 'lcov'],
    },
    globals: true,
    include: ['tests/**/*.test.ts'],
  },
})
