import { defineConfig } from 'vite-plus'

const ignorePatterns = [
  'node_modules',
  'dist',
  'report',
  'coverage',
  '**/*.d.ts',
  '.github',
  'README.md',
  'articles',
]

export default defineConfig({
  staged: { '*': 'vp check --fix' },
  pack: { clean: true, dts: true, entry: ['src/index.ts'], format: ['esm'], sourcemap: true },
  fmt: {
    experimentalSortImports: {
      groups: [
        'type-import',
        ['value-builtin', 'value-external'],
        'type-internal',
        'value-internal',
        ['type-parent', 'type-sibling', 'type-index'],
        ['value-parent', 'value-sibling', 'value-index'],
        'unknown',
      ],
    },
    ignorePatterns,
    objectWrap: 'collapse',
    semi: false,
    singleQuote: true,
  },
  lint: {
    categories: {
      correctness: 'error',
      suspicious: 'error',
      perf: 'error',
      restriction: 'error',
      style: 'error',
      pedantic: 'error',
      nursery: 'off',
    },
    ignorePatterns,
    options: { typeAware: true, typeCheck: true },
    rules: {
      'consistent-indexed-object-style': 'allow',
      'consistent-type-definitions': 'allow',
      'consistent-type-imports': 'error',
      'capitalized-comments': 'allow',
      'eslint/max-classes-per-file': ['error', { max: 10 }],
      'eslint/max-lines-per-function': [
        'error',
        { max: 220, skipBlankLines: false, skipComments: false, IIFEs: false },
      ],
      'eslint/max-statements': ['error', { max: 35 }],
      'max-lines': 'allow',
      'explicit-function-return-type': 'allow',
      'explicit-module-boundary-types': 'allow',
      'func-names': 'allow',
      'func-style': 'allow',
      curly: 'allow',
      'id-length': 'allow',
      'init-declarations': 'allow',
      'new-cap': 'allow',
      'no-array-method-this-argument': 'allow',
      'no-async-await': 'allow',
      'no-console': 'allow',
      'no-duplicate-imports': 'allow',
      'no-inline-comments': 'allow',
      'no-lonely-if': 'allow',
      'no-magic-numbers': 'allow',
      'no-misused-promises': 'allow',
      'no-nested-ternary': 'allow',
      'no-optional-chaining': 'allow',
      'no-plusplus': 'allow',
      'no-rest-spread-properties': 'allow',
      'no-shadow': 'allow',
      'no-ternary': 'allow',
      'no-undefined': 'allow',
      'no-use-before-define': 'allow',
      'promise-function-async': 'allow',
      'prefer-destructuring': 'allow',
      'prefer-template': 'allow',
      'prefer-exponentiation-operator': 'allow',
      'prefer-readonly-parameter-types': 'allow',
      'require-await': 'allow',
      'return-await': 'allow',
      'sort-imports': 'allow',
      'sort-keys': 'allow',
      'strict-boolean-expressions': 'allow',
      'strict-void-return': 'allow',
      'switch-case-braces': 'allow',
      '@typescript-eslint/ban-types': 'allow',
      '@typescript-eslint/consistent-return': 'allow',
      '@typescript-eslint/no-empty-object-type': 'allow',
      '@typescript-eslint/no-base-to-string': 'allow',
      '@typescript-eslint/no-deprecated': 'allow',
      '@typescript-eslint/no-explicit-any': 'allow',
      '@typescript-eslint/no-misused-promises': 'allow',
      '@typescript-eslint/no-invalid-void-type': 'allow',
      '@typescript-eslint/no-unnecessary-type-arguments': 'allow',
      '@typescript-eslint/no-unnecessary-type-parameters': 'allow',
      '@typescript-eslint/no-unsafe-argument': 'allow',
      '@typescript-eslint/no-unsafe-assignment': 'allow',
      '@typescript-eslint/no-unsafe-call': 'allow',
      '@typescript-eslint/no-unsafe-member-access': 'allow',
      '@typescript-eslint/no-unsafe-return': 'allow',
      '@typescript-eslint/no-unsafe-type-assertion': 'allow',
      '@typescript-eslint/parameter-properties': 'allow',
      '@typescript-eslint/promise-function-async': 'allow',
      '@typescript-eslint/return-await': 'allow',
      '@typescript-eslint/strict-boolean-expressions': 'allow',
      '@typescript-eslint/strict-void-return': 'allow',
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'allow',
      'unicorn/consistent-function-scoping': 'allow',
      'unicorn/custom-error-definition': 'allow',
      'unicorn/filename-case': ['error', { case: 'kebabCase' }],
      'unicorn/no-array-callback-reference': 'allow',
      'unicorn/no-null': 'allow',
      'unicorn/no-thenable': 'allow',
      'unicorn/no-useless-undefined': 'allow',
      yoda: 'allow',
    },
    overrides: [
      {
        files: ['**/tests/**', '**/test/**'],
        rules: {
          '@typescript-eslint/await-thenable': 'allow',
          '@typescript-eslint/no-explicit-any': 'allow',
          '@typescript-eslint/no-confusing-void-expression': 'allow',
          '@typescript-eslint/no-unsafe-type-assertion': 'allow',
          '@typescript-eslint/require-await': 'allow',
          'eslint/max-depth': 'allow',
          'eslint/no-await-in-loop': 'allow',
          'max-depth': 'allow',
          'max-lines': ['error', { max: 2000, skipBlankLines: true, skipComments: true }],
          'max-lines-per-function': 'allow',
          'no-async-await': 'allow',
          'no-constant-condition': 'allow',
          'no-console': 'allow',
          'no-lonely-if': 'allow',
          'no-magic-numbers': 'allow',
          'no-new': 'allow',
          'no-undefined': 'allow',
          'unicorn/consistent-function-scoping': 'allow',
          'unicorn/custom-error-definition': 'allow',
          'unicorn/no-await-expression-member': 'allow',
          'unicorn/prefer-event-target': 'allow',
        },
      },
    ],
  },
  test: {
    coverage: {
      exclude: ['node_modules/', 'dist/', 'tests/'],
      reporter: ['text', 'json', 'html', 'lcov'],
    },
    globals: true,
    include: ['tests/**/*.test.ts'],
  },
})
