import { defineConfig, type UserConfig } from "vite-plus";

const ignorePatterns = [
  "node_modules",
  "dist",
  "report",
  "coverage",
  "**/*.d.ts",
  ".github",
  "README.md",
  "**/CHANGELOG.md",
];

const config: UserConfig = defineConfig({
  staged: { "*": "vp check --fix" },
  pack: {
    checks: { legacyCjs: false },
    clean: true,
    dts: { sourcemap: false },
    deps: { onlyBundle: false },
    entry: ["src/cli.ts"],
    format: ["esm", "cjs"],
    outExtensions: ({ format }) => ({ dts: ".d.ts", js: format === "cjs" ? ".cjs" : ".js" }),
    sourcemap: false,
  },
  fmt: { ignorePatterns, objectWrap: "collapse" },
  lint: {
    categories: {
      correctness: "error",
      nursery: "off",
      pedantic: "error",
      perf: "error",
      restriction: "error",
      style: "error",
      suspicious: "error",
    },
    ignorePatterns,
    options: { typeAware: true, typeCheck: true },
    rules: {
      "capitalized-comments": "allow",
      complexity: "allow",
      "consistent-type-definitions": "allow",
      curly: "allow",
      "explicit-function-return-type": "allow",
      "func-style": "allow",
      "max-lines": "allow",
      "max-lines-per-function": "allow",
      "max-params": "allow",
      "max-statements": "allow",
      "no-async-await": "allow",
      "no-bitwise": "allow",
      "no-continue": "allow",
      "no-console": "allow",
      "no-magic-numbers": "allow",
      "no-map-spread": "allow",
      "no-optional-chaining": "allow",
      "no-rest-spread-properties": "allow",
      "no-ternary": "allow",
      "no-undefined": "allow",
      "one-var": "allow",
      "no-use-before-define": "allow",
      "no-void": "allow",
      "new-cap": "allow",
      "prefer-readonly-parameter-types": "allow",
      "require-unicode-regexp": "allow",
      "require-await": "allow",
      "sort-keys": "allow",
      "sort-imports": "allow",
      "unicorn/filename-case": ["error", { case: "kebabCase" }],
      "unicorn/import-style": "allow",
      "unicorn/no-object-as-default-parameter": "allow",
    },
    overrides: [
      {
        files: ["**/scripts/**"],
        rules: {
          "no-unsafe-type-assertion": "allow",
          "no-magic-numbers": "allow",
          "prefer-template": "allow",
          "unicorn/consistent-function-scoping": "allow",
        },
      },
    ],
  },
});

export default config;
