import { defineConfig, type UserConfig } from "vite-plus";

const ignorePatterns = [
  "node_modules",
  "dist",
  "report",
  "coverage",
  "**/*.d.ts",
  ".github",
  "README.md",
];

const config: UserConfig = defineConfig({
  staged: { "*": "vp check --fix" },
  pack: {
    clean: true,
    dts: true,
    deps: { onlyBundle: false },
    entry: ["src/cli.ts"],
    format: ["esm"],
    outExtensions: () => ({ dts: ".d.ts", js: ".js" }),
    sourcemap: true,
  },
  fmt: { ignorePatterns, objectWrap: "collapse" },
  lint: {
    categories: {
      correctness: "error",
      nursery: "off",
      pedantic: "error",
      perf: "error",
      restriction: "error",
      style: "error",
      suspicious: "error",
    },
    ignorePatterns,
    options: { typeAware: true, typeCheck: true },
    rules: {
      "@typescript-eslint/no-base-to-string": "allow",
      "@typescript-eslint/no-non-null-assertion": "allow",
      "@typescript-eslint/no-unnecessary-type-arguments": "allow",
      "@typescript-eslint/no-unsafe-type-assertion": "allow",
      "@typescript-eslint/strict-void-return": "allow",
      "capitalized-comments": "allow",
      complexity: "allow",
      "consistent-type-definitions": "allow",
      curly: "allow",
      "eslint/complexity": "allow",
      "eslint/max-statements": "allow",
      "eslint/require-unicode-regexp": "allow",
      "eslint/sort-imports": "allow",
      "explicit-function-return-type": "allow",
      "func-style": "allow",
      "max-lines": "allow",
      "max-lines-per-function": "allow",
      "max-params": "allow",
      "max-statements": "allow",
      "no-async-await": "allow",
      "no-bitwise": "allow",
      "no-console": "allow",
      "no-magic-numbers": "allow",
      "no-optional-chaining": "allow",
      "no-rest-spread-properties": "allow",
      "no-ternary": "allow",
      "no-undefined": "allow",
      "no-use-before-define": "allow",
      "new-cap": "allow",
      "prefer-destructuring": "allow",
      "prefer-readonly-parameter-types": "allow",
      "require-unicode-regexp": "allow",
      "require-await": "allow",
      "sort-keys": "allow",
      "sort-imports": "allow",
      "strict-void-return": "allow",
      "unicorn/filename-case": ["error", { case: "kebabCase" }],
      "unicorn/import-style": "allow",
      "unicorn/prefer-string-replace-all": "allow",
      "unicorn/prefer-top-level-await": "allow",
    },
  },
});

export default config;
