import { resolve } from "node:path";

import type { ResultarLintFinding, ResultarRuleName } from "./finding.js";
import { type NoDiscardMode, type ResultarLintResult, findResultarLintFindings } from "./lint.js";
import { type ResultarRulesOptions, onlyResultarRule, resultarRuleNames } from "./rules-core.js";

interface OxlintLineColumn {
  readonly column: number;
  readonly line: number;
}

interface OxlintDiagnostic {
  readonly loc: OxlintLineColumn;
  readonly message: string;
}

interface OxlintContext {
  readonly cwd: string;
  readonly filename: string;
  readonly options: readonly unknown[];
  readonly physicalFilename: string;
  report(diagnostic: OxlintDiagnostic): void;
}

interface OxlintRule {
  readonly meta: {
    readonly docs: { readonly description: string; readonly recommended: boolean };
    readonly messages: Record<string, string>;
    readonly schema: readonly unknown[];
    readonly type: "problem";
  };
  createOnce(context: OxlintContext): { Program(): void };
}

interface OxlintPlugin {
  readonly meta: { readonly name: "resultar" };
  readonly rules: Record<ResultarRuleName, OxlintRule>;
}

interface RuleOptions {
  readonly mode?: NoDiscardMode;
  readonly project?: string;
}

const defaultProject = "tsconfig.json";
const resultsByProject = new Map<string, ResultarLintResult>();
const reportedProjectFailures = new Set<string>();

const ruleDescriptions: Record<ResultarRuleName, string> = {
  "no-discard": "Require Resultar Result values to be handled or explicitly discarded.",
  "no-tagged-error-constructor-override":
    "Prevent overriding constructors generated by createTaggedError.",
  "no-try-catch-in-safe-try":
    "Prefer Resultar error mapping helpers over try/catch inside safeTry.",
  "no-useless-recovery": "Disallow recovery calls on Resultar values whose error channel is never.",
  "prefer-and-then":
    "Prefer andThen or asyncAndThen when a Resultar map callback returns a Result.",
  "prefer-map-err": "Prefer mapErr when orElse only replaces a failure with another Err.",
  "prefer-tagged-error": "Prefer createTaggedError for Resultar error channels.",
  "tagged-error-name-match": "Require createTaggedError names to match their class names.",
  "typed-catch-mapper":
    "Require try/catch conversion helpers to map caught values to typed errors.",
  "unsafe-result-type-assertion": "Prevent assertions that narrow Resultar error channels.",
  "yield-star-in-safe-try": "Require yield* when unwrapping Resultar values inside safeTry.",
};

const isRecord = (value: unknown): value is Record<PropertyKey, unknown> =>
  typeof value === "object" && value !== null;

const normalizePath = (cwd: string, fileName: string): string =>
  resolve(cwd, fileName).replaceAll(/\\/g, "/");

const parseRuleOptions = (options: readonly unknown[]): RuleOptions => {
  const firstOption = options[0];

  if (!isRecord(firstOption)) {
    return {};
  }

  const mode = firstOption.mode === "direct" ? "direct" : "must-use";

  if (typeof firstOption.project !== "string") {
    return { mode };
  }

  const project = firstOption.project.trim();

  return project === "" ? { mode } : { mode, project };
};

const getProjectPath = (context: OxlintContext): string => {
  const { project = defaultProject } = parseRuleOptions(context.options);

  return project;
};

const getMode = (context: OxlintContext): NoDiscardMode =>
  parseRuleOptions(context.options).mode ?? "must-use";

const getRuleOptions = (
  ruleName: ResultarRuleName,
  context: OxlintContext,
): Partial<ResultarRulesOptions> => ({
  ...onlyResultarRule(ruleName, "error"),
  noDiscardMode: getMode(context),
});

const getCacheKey = (
  cwd: string,
  project: string,
  ruleName: ResultarRuleName,
  mode: NoDiscardMode,
): string =>
  `${normalizePath(process.cwd(), cwd)}\0${normalizePath(cwd, project)}\0${ruleName}\0${mode}`;

const getProjectResult = (
  context: OxlintContext,
  ruleName: ResultarRuleName,
): readonly [string, ResultarLintResult] => {
  const project = getProjectPath(context);
  const mode = getMode(context);
  const cacheKey = getCacheKey(context.cwd, project, ruleName, mode);
  const cachedResult = resultsByProject.get(cacheKey);

  if (cachedResult !== undefined) {
    return [cacheKey, cachedResult];
  }

  const result = findResultarLintFindings({
    project,
    rootDir: context.cwd,
    rules: getRuleOptions(ruleName, context),
  });
  resultsByProject.set(cacheKey, result);

  return [cacheKey, result];
};

const getContextFileName = (context: OxlintContext): string =>
  context.physicalFilename === "<text>" ? context.filename : context.physicalFilename;

const isFindingForContextFile = (context: OxlintContext, finding: ResultarLintFinding): boolean =>
  normalizePath(context.cwd, finding.file) ===
  normalizePath(context.cwd, getContextFileName(context));

const reportProjectFailure = (
  context: OxlintContext,
  cacheKey: string,
  result: Extract<ResultarLintResult, { readonly ok: false }>,
): void => {
  if (reportedProjectFailures.has(cacheKey)) {
    return;
  }

  reportedProjectFailures.add(cacheKey);
  context.report({
    loc: { column: 0, line: 1 },
    message: `Resultar check failed: ${result.error.message}`,
  });
};

const reportProjectFindings = (context: OxlintContext, ruleName: ResultarRuleName): void => {
  const [cacheKey, result] = getProjectResult(context, ruleName);

  if (!result.ok) {
    reportProjectFailure(context, cacheKey, result);
    return;
  }

  for (const finding of result.findings) {
    if (finding.rule === ruleName && isFindingForContextFile(context, finding)) {
      context.report({
        loc: { column: Math.max(0, finding.column - 1), line: finding.line },
        message: finding.message,
      });
    }
  }
};

const ruleSchema = [
  {
    additionalProperties: false,
    properties: {
      mode: { enum: ["direct", "must-use"], type: "string" },
      project: { type: "string" },
    },
    type: "object",
  },
];

const createRule = (ruleName: ResultarRuleName): OxlintRule => ({
  meta: {
    docs: { description: ruleDescriptions[ruleName], recommended: ruleName === "no-discard" },
    messages: { finding: ruleDescriptions[ruleName] },
    schema: ruleSchema,
    type: "problem",
  },
  createOnce(context) {
    return {
      Program() {
        reportProjectFindings(context, ruleName);
      },
    };
  },
});

const rules = Object.fromEntries(
  resultarRuleNames.map((ruleName) => [ruleName, createRule(ruleName)]),
) as Record<ResultarRuleName, OxlintRule>;

const plugin: OxlintPlugin = { meta: { name: "resultar" }, rules };

export default plugin;
