import { defineConfig, type UserConfig } from "vite-plus";

const ignorePatterns = [
  "node_modules",
  "dist",
  "report",
  "coverage",
  "**/*.d.ts",
  ".github",
  "README.md",
];

const config: UserConfig = defineConfig({
  staged: { "*": "vp check --fix" },
  pack: {
    clean: true,
    dts: true,
    deps: { onlyBundle: false },
    entry: ["src/index.ts"],
    format: ["esm"],
    outExtensions: () => ({ dts: ".d.ts", js: ".js" }),
    sourcemap: true,
  },
  fmt: { ignorePatterns, objectWrap: "collapse" },
  lint: {
    categories: {
      correctness: "error",
      nursery: "off",
      pedantic: "error",
      perf: "error",
      restriction: "error",
      style: "error",
      suspicious: "error",
    },
    ignorePatterns,
    options: { typeAware: true, typeCheck: true },
    rules: {
      "@typescript-eslint/no-confusing-void-expression": "allow",
      "@typescript-eslint/no-invalid-void-type": "allow",
      "@typescript-eslint/consistent-type-imports": "allow",
      "@typescript-eslint/explicit-member-accessibility": "allow",
      "@typescript-eslint/parameter-properties": "allow",
      "@typescript-eslint/promise-function-async": "allow",
      "@typescript-eslint/no-unnecessary-type-arguments": "allow",
      "@typescript-eslint/no-unsafe-type-assertion": "allow",
      "@typescript-eslint/strict-void-return": "allow",
      "@typescript-eslint/unified-signatures": "allow",
      "capitalized-comments": "allow",
      "consistent-type-definitions": "allow",
      curly: "allow",
      "eslint/max-classes-per-file": ["error", { max: 10 }],
      "explicit-function-return-type": "allow",
      "func-style": "allow",
      "id-length": "allow",
      "max-lines": "allow",
      "max-lines-per-function": "allow",
      "max-params": "allow",
      "max-statements": "allow",
      "no-async-await": "allow",
      "no-magic-numbers": "allow",
      "new-cap": "allow",
      "no-optional-chaining": "allow",
      "no-rest-spread-properties": "allow",
      "no-ternary": "allow",
      "no-undefined": "allow",
      "one-var": "allow",
      "no-use-before-define": "allow",
      "prefer-destructuring": "allow",
      "prefer-readonly-parameter-types": "allow",
      "require-await": "allow",
      "sort-imports": "allow",
      "sort-keys": "allow",
      "strict-void-return": "allow",
      "unicorn/catch-error-name": "allow",
      "unicorn/filename-case": ["error", { case: "kebabCase" }],
      "unicorn/import-style": "allow",
      "unicorn/switch-case-braces": "allow",
    },
    overrides: [
      {
        files: ["**/tests/**", "**/test/**", "scripts/**/*.ts"],
        rules: {
          "@typescript-eslint/require-await": "allow",
          "@typescript-eslint/strict-boolean-expressions": "allow",
          "max-lines": ["error", { max: 2000, skipBlankLines: true, skipComments: true }],
          "no-magic-numbers": "allow",
          "prefer-template": "allow",
          "unicorn/consistent-function-scoping": "allow",
        },
      },
    ],
  },
  test: {
    coverage: {
      exclude: ["node_modules/", "dist/", "tests/", "src/index.ts"],
      reporter: ["text", "json", "html", "lcov"],
    },
    globals: true,
    include: ["tests/**/*.test.ts"],
    testTimeout: 15_000,
  },
});

export default config;
